name: 'mirror'
on:
  push:
    branches:
        - mirror
  schedule:
    # Run everyday at 3 AM UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v3
        with:
          origin: 'https://git.ieeeucsd.org/Webmaster/old-ieeeucsd-org'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
